version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  # Specify the Node.js version you need
    commands:
      - pwd
      - ls
      - cd react-hello-world-app
      - echo one phase done

  build:
    commands:
      - echo two phase done
