version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  # Specify the Node.js version you need
    commands:
      - pwd
      - ls
      - npm install
      - echo one phase done****************

  build:
    commands:
      - npm run build
      - pwd
      - ls
      - mkdir ~/react-hello-world-app
      - mv build ~/react-hello-world-app
      - ls ~/react-hello-world-app
      - cd ~/react-hello-world-app/build
      - ls
      - echo two phase done******************

artifacts:
  files:
    - '**/*'
  base-directory: ~/react-hello-world-app  # Adjust this if your build output is in a different directory
