version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  # Specify the Node.js version you need
    commands:
      - pwd
      - ls
      - npm install
      - echo one phase done****************

  build:
    commands:
      - npm run build
      - pwd
      - ls
      - mkdir -p /home/ubuntu/react-hello-world-app
      - mv build /home/ubuntu/react-hello-world-app
      - ls /home/ubuntu/react-hello-world-app
      - echo two phase done******************

artifacts:
  files:
    - '**/*'
  base-directory: /home/ubuntu/react-hello-world-app  # Adjust this if your build output is in a different directory
